trigger:
- master
- refs/tags/v*

jobs:

#
# Windows
#

- job: Windows
  pool:
    vmImage: 'windows-latest'

  variables:
    solution: 'password-manager-access.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

#
# Linux
#

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    framework: 'netcoreapp3.0'
    solution: 'password-manager-access.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - bash: 'dotnet restore $(solution)'
    displayName: Restore

  - bash: 'dotnet build -c $(buildConfiguration) --no-restore $(solution)'
    displayName: Build

  - bash: 'dotnet test -c $(buildConfiguration) --framework $(framework) --logger trx --no-build $(solution)'
    displayName: Test

  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFormat: VSTest
      testResultsFiles: test/TestResults/*.trx

#
# Release to GitHub
#

- job: Release

  dependsOn:
  - Windows
  - Linux

  condition: startsWith(variables['build.sourceBranch'], 'refs/tags/v')

  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - bash: 'ci/make-nuget-package.sh $(Build.SourceBranchName)'
    displayName: Build package

  - bash: ci/push-package-to-nuget.sh
    displayName: Push package
    env:
      NUGET_API_KEY: $(nuget_api_key)

  - task: GitHubRelease@0
    inputs:
      gitHubConnection: github-release
      assets: $(Pipeline.Workspace)/**/*.nupkg
      tagSource: manual
      tag: $(Build.SourceBranchName)

  - task: DotNetCoreCLI@2
    condition: false
    inputs:
      command: push
      searchPatternPush: $(Pipeline.Workspace)/**/*.nupkg
      nugetFeedType: external
      externalEndPoint: nuget-push
