trigger:
- master

jobs:
- job: Windows
  pool:
    vmImage: 'windows-latest'

  variables:
    solution: 'password-manager-access.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'

  steps:
  - task: NuGetToolInstaller@1

  - task: NuGetCommand@2
    inputs:
      restoreSolution: '$(solution)'

  - task: VSBuild@1
    inputs:
      solution: '$(solution)'
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: VSTest@2
    inputs:
      platform: '$(buildPlatform)'
      configuration: '$(buildConfiguration)'

  - task: NuGetCommand@2
    inputs:
      command: pack
      packagesToPack: 'src/*.csproj'

  # - task: GithubRelease@0
  #   displayName: 'Create GitHub Release'
  #   condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  #   inputs:
  #     gitHubConnection: detunized
  #     assets: $(Build.ArtifactStagingDirectory)/*.nupkg

- job: Linux
  pool:
    vmImage: 'ubuntu-latest'

  variables:
    framework: 'netcoreapp3.0'

  steps:
  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: restore

  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: build

  - task: DotNetCoreCLI@2
    displayName: Test
    inputs:
      command: test
      arguments: '--framework $(framework)'
