name: .NET build, test and release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest

    env:
      framework: net6
      solution: password-manager-access.sln
      buildPlatform: Any CPU
      buildConfiguration: Release

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Info
      run: |
        dotnet --info
        dotnet --list-sdks
        dotnet --list-runtimes

    - name: Restore
      run: dotnet restore $solution

    - name: Build
      run: dotnet build --configuration $buildConfiguration --no-restore $solution

    - name: Test
      run: dotnet test --configuration $buildConfiguration --framework $framework --logger "trx;LogFileName=test-results.trx" --no-build $solution

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: .NET Tests
        path: test-results.trx
        reporter: dotnet-trx
