name: .NET build, test and release

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  Build:
    # TODO: enable this after testing
    if: false

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: [net6]
        include:
          - os: windows-latest
            framework: net48

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: .NET info
        run: |
            dotnet --info
            dotnet --list-sdks
            dotnet --list-runtimes

      - name: Test ${{ matrix.framework }}
        run: dotnet test --configuration Release --framework ${{ matrix.framework }} --logger "trx;LogFileName=test-results.trx"

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Test (${{ matrix.os }}, ${{ matrix.framework }})
          path: test/TestResults/test-results.trx
          reporter: dotnet-trx

  Release:
    # TODO: enable this after testing
    # needs: Build
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest

    steps:
      - name: Build
        run: |
          pwd
          ls -l
          ./ci/make-nuget-package.sh ${{ github.ref_name }}

      - name: Push
        run: |
          pwd
          ls -l
          ./ci/push-package-to-nuget.sh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/**/*.nupkg
          tag_name: $${{ github.ref_name }}

