name: .NET build, test and release

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux:
    runs-on: ubuntu-latest

    env:
      framework: 'netcoreapp3.0'
      solution: 'password-manager-access.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 3.1.x

    - name: Info
      run: |
        dotnet --info
        dotnet --list-sdks
        dotnet --list-runtimes

    - name: Restore
      run: dotnet restore $solution

    - name: Build
      run: dotnet build -c $buildConfiguration --no-restore $solution

    - name: Test
      run: |
        dotnet test -c $buildConfiguration --framework $framework --no-build $solution || true
        dotnet test -c Release --framework net48 --no-build password-manager-access.sln || true
        dotnet test -c Release --framework netcoreapp3.0 --no-build password-manager-access.sln || true
        dotnet test -c Release --framework netcoreapp3.1 --no-build password-manager-access.sln || true
        dotnet test password-manager-access.sln || true
